using System;
using System.Data;
using System.Threading.Tasks;
using Oracle.ManagedDataAccess.Client;
using Dapper;
using Neo4j.Driver;

namespace SGRC.App.Data
{
    public class DatabaseManager 
    {
        private readonly string _oracleConn = "User Id=system;Password=SGRC_ADMIN_E7_G600;Data Source=localhost:1521/XE;";
        
        private readonly IDriver _neo4jDriver;

        public DatabaseManager()
        {
           _neo4jDriver = GraphDatabase.Driver("bolt://localhost:7687", AuthTokens.Basic("neo4j", "SGRC_ADMIN_E7_G600"));
        }

        private async Task PrepararTablasOracle()
        {
            using (var conn = new OracleConnection(_oracleConn))
            {
                await conn.OpenAsync();
                
                try
                {
                    await conn.ExecuteAsync(@"
                        CREATE TABLE ALIMENTOS (
                            ID_ALIMENTO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            NOMBRE VARCHAR2(100) NOT NULL,
                            CATEGORIA VARCHAR2(50) NOT NULL,
                            UNIDAD_MEDIDA VARCHAR2(20) NOT NULL
                        )");
                }
                catch (OracleException ex) when (ex.Number == 955) { /* Ignorar */ }

                try
                {
                    await conn.ExecuteAsync(@"
                        CREATE TABLE LOTES_INGRESO (
                            ID_LOTE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ID_ALIMENTO NUMBER NOT NULL,
                            CANTIDAD NUMBER(10, 2) NOT NULL,
                            FECHA_INGRESO DATE DEFAULT SYSDATE NOT NULL,
                            FECHA_CADUCIDAD DATE NOT NULL,
                            ESTADO VARCHAR2(20) DEFAULT 'DISPONIBLE',
                            ID_TRABAJADOR NUMBER NOT NULL
                        )");
                }
                catch (OracleException ex) when (ex.Number == 955) { /* Ignorar */ }
            }
        }

        public async Task<System.Collections.Generic.IEnumerable<AlimentoItem>> ObtenerInventario()
        {
            using (var conn = new OracleConnection(_oracleConn))
            {
                await conn.OpenAsync();
                // Traemos todos los alimentos ordenados del más nuevo al más viejo
                return await conn.QueryAsync<AlimentoItem>("SELECT * FROM ALIMENTOS ORDER BY ID_ALIMENTO DESC");
            }
        }

        public async Task RegistrarAlimentoCompleto(string nombre, decimal cantidad, DateTime caducidad, string donante)
        {
            await PrepararTablasOracle();

            // GUARDAR INVENTARIO EN ORACLE
            using (var conn = new OracleConnection(_oracleConn))
            {
                await conn.OpenAsync();

                int idAlimento = await conn.QueryFirstOrDefaultAsync<int>(
                    "SELECT ID_ALIMENTO FROM ALIMENTOS WHERE NOMBRE = :nom", 
                    new { nom = nombre });
                
                if (idAlimento == 0)
                {
                    await conn.ExecuteAsync(
                        "INSERT INTO ALIMENTOS (NOMBRE, CATEGORIA, UNIDAD_MEDIDA) VALUES (:nom, 'General', 'Kg')", 
                        new { nom = nombre });
                        
                    idAlimento = await conn.QueryFirstOrDefaultAsync<int>(
                        "SELECT ID_ALIMENTO FROM ALIMENTOS WHERE NOMBRE = :nom", 
                        new { nom = nombre });
                }
                
                await conn.ExecuteAsync(
                    "INSERT INTO LOTES_INGRESO (ID_ALIMENTO, CANTIDAD, FECHA_CADUCIDAD, ID_TRABAJADOR) VALUES (:idAlim, :cant, :cad, 1)", 
                    new { idAlim = idAlimento, cant = cantidad, cad = caducidad });
            }

            // GUARDAR RELACIÓN EN NEO4J
            using (var session = _neo4jDriver.AsyncSession())
            {
                var cypher = "MERGE (d:Donante {nombre: $donante}) CREATE (d)-[:DONO]->(:Alimento {nombre: $prod})";
                var cursor = await session.RunAsync(cypher, new { donante = donante, prod = nombre });
                
                await cursor.ConsumeAsync();
            }
        }

        public void Dispose()
        {
            _neo4jDriver?.Dispose();
        }
    }

    public class AlimentoItem
    {
        public int ID_ALIMENTO { get; set; }
        public string NOMBRE { get; set; }
        public string CATEGORIA { get; set; }
        public string UNIDAD_MEDIDA { get; set; }
    }
}