using System;
using System.Data;
using System.Threading.Tasks;
using Oracle.ManagedDataAccess.Client;
using Dapper;
using Neo4j.Driver;
using System.Collections.Generic;

namespace SGRC.App.Data
{
    public interface IObserver // Patron Observer para actualizar estadisticas en la vista de inventario cuando se registren nuevos alimentos
    { 
        void UpdateStats(); 
    }
    
    public interface ISubject 
    {
        void Attach(IObserver observer);
        void Notify();
    }

    public class InventarioNotifier : ISubject 
    {
        private static InventarioNotifier _instancia;
        
        // Patron Singleton combinado para asegurar una sola instancia del notificador
        public static InventarioNotifier Instancia => _instancia ??= new InventarioNotifier();
        private readonly List<IObserver> _observers = new();
        
        public void Attach(IObserver observer) 
        { 
            _observers.Add(observer); 
        }

        public void Notify() 
        { 
            foreach(var obs in _observers) 
            {
                obs.UpdateStats();
            }
        }
    }

    public class DatabaseManager 
    {
        private static DatabaseManager _instancia;
        public static DatabaseManager Instancia => _instancia ??= new DatabaseManager();
        private readonly string _oracleConn = "User Id=system;Password=SGRC_ADMIN_E7_G600;Data Source=localhost:1521/XE;";
        private readonly IDriver _neo4jDriver;

        private DatabaseManager()
        {
           _neo4jDriver = GraphDatabase.Driver("bolt://localhost:7687", AuthTokens.Basic("neo4j", "SGRC_ADMIN_E7_G600"));
        }

        private async Task PrepararTablasOracle()
        {
            using (var conn = new OracleConnection(_oracleConn))
            {
                await conn.OpenAsync();
                try 
                { 
                    await conn.ExecuteAsync(@"CREATE TABLE ALIMENTOS 
                                            (ID_ALIMENTO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                                            NOMBRE VARCHAR2(100) NOT NULL, 
                                            CATEGORIA VARCHAR2(50) NOT NULL, 
                                            UNIDAD_MEDIDA VARCHAR2(20) NOT NULL)"); 
                } 
                catch (OracleException ex) when (ex.Number == 955) { }
                try 
                { 
                    await conn.ExecuteAsync(@"CREATE TABLE LOTES_INGRESO 
                                            (ID_LOTE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                                            ID_ALIMENTO NUMBER NOT NULL, 
                                            CANTIDAD NUMBER(10, 2) NOT NULL, 
                                            FECHA_INGRESO DATE DEFAULT SYSDATE NOT NULL, 
                                            FECHA_CADUCIDAD DATE NOT NULL, 
                                            ESTADO VARCHAR2(20) DEFAULT 'DISPONIBLE', 
                                            ID_TRABAJADOR NUMBER NOT NULL)"); 
                } 
                catch (OracleException ex) when (ex.Number == 955) { }
            }
        }

        public async Task<int> ObtenerProductosCriticos()
        {
            using var conn = new OracleConnection(_oracleConn);
            return await conn.QueryFirstOrDefaultAsync<int>("SELECT COUNT(*) FROM LOTES_INGRESO WHERE FECHA_CADUCIDAD <= SYSDATE + 7 AND ESTADO = 'DISPONIBLE'");
        }

        public async Task<decimal> ObtenerDonacionesHoy()
        {
            using var conn = new OracleConnection(_oracleConn);
            return await conn.QueryFirstOrDefaultAsync<decimal>("SELECT NVL(SUM(CANTIDAD), 0) FROM LOTES_INGRESO WHERE TRUNC(FECHA_INGRESO) = TRUNC(SYSDATE)");
        }

        public async Task<IEnumerable<InventarioDTO>> ObtenerInventarioCompleto()
        {
            using var conn = new OracleConnection(_oracleConn);
            string sql = @"
                SELECT L.ID_LOTE, A.NOMBRE, A.CATEGORIA, L.CANTIDAD, A.UNIDAD_MEDIDA, L.FECHA_INGRESO, L.FECHA_CADUCIDAD
                FROM ALIMENTOS A
                JOIN LOTES_INGRESO L ON A.ID_ALIMENTO = L.ID_ALIMENTO
                WHERE L.ESTADO = 'DISPONIBLE'
                ORDER BY L.FECHA_INGRESO DESC";
            return await conn.QueryAsync<InventarioDTO>(sql);
        }

        public async Task RegistrarAlimentoCompleto(string nombre, decimal cantidad, DateTime caducidad, string donante)
        {
            await PrepararTablasOracle();

            // GUARDAR INVENTARIO EN ORACLE
            using (var conn = new OracleConnection(_oracleConn))
            {
                await conn.OpenAsync();

                int idAlimento = await conn.QueryFirstOrDefaultAsync<int>(
                    "SELECT ID_ALIMENTO FROM ALIMENTOS WHERE NOMBRE = :nom", 
                    new { nom = nombre });
                
                if (idAlimento == 0)
                {
                    await conn.ExecuteAsync(
                        "INSERT INTO ALIMENTOS (NOMBRE, CATEGORIA, UNIDAD_MEDIDA) VALUES (:nom, 'General', 'Kg')", 
                        new { nom = nombre });
                        
                    idAlimento = await conn.QueryFirstOrDefaultAsync<int>(
                        "SELECT ID_ALIMENTO FROM ALIMENTOS WHERE NOMBRE = :nom", 
                        new { nom = nombre });
                }
                
                await conn.ExecuteAsync(
                    "INSERT INTO LOTES_INGRESO (ID_ALIMENTO, CANTIDAD, FECHA_CADUCIDAD, ID_TRABAJADOR) VALUES (:idAlim, :cant, :cad, 1)", 
                    new { idAlim = idAlimento, cant = cantidad, cad = caducidad });
            }

            // GUARDAR RELACIÓN EN NEO4J
            using (var session = _neo4jDriver.AsyncSession())
            {
                var cypher = "MERGE (d:Donante {nombre: $donante}) CREATE (d)-[:DONO]->(:Alimento {nombre: $prod})";
                await session.RunAsync(cypher, new { donante = donante, prod = nombre });
            }

            // Patron observer: Disparamos la notificacion de que el inventario cambio
            InventarioNotifier.Instancia.Notify();
        }

        public async Task EliminarLote(int idLote)
        {
            using var conn = new OracleConnection(_oracleConn);
            await conn.ExecuteAsync("UPDATE LOTES_INGRESO SET ESTADO = 'ELIMINADO' WHERE ID_LOTE = :id", new { id = idLote });

            // Patron observer: Avisamos que se elimino algo para actualizar las tarjetas
            InventarioNotifier.Instancia.Notify();
        }

        public async Task ActualizarLote(int idLote, decimal nuevaCantidad, DateTime nuevaCaducidad)
        {
            using var conn = new OracleConnection(_oracleConn);
            await conn.ExecuteAsync("UPDATE LOTES_INGRESO SET CANTIDAD = :cant, FECHA_CADUCIDAD = :cad WHERE ID_LOTE = :id", 
                new { cant = nuevaCantidad, cad = nuevaCaducidad, id = idLote });
            InventarioNotifier.Instancia.Notify();
        }

        public void Dispose()
        {
            _neo4jDriver?.Dispose();
        }
    }

    public class InventarioDTO
    {
        public int ID_LOTE 
        { 
            get; 
            set; 
        }

        public string NOMBRE
        { 
            get; 
            set; 
        }

        public string CATEGORIA
        { 
            get; 
            set; 
        }

        public decimal CANTIDAD
        { 
            get; 
            set; 
        }

        public string UNIDAD_MEDIDA
        { 
            get; 
            set; 
        }

        public DateTime FECHA_INGRESO
        { 
            get; 
            set; 
        }

        public DateTime FECHA_CADUCIDAD 
        { 
            get; 
            set; 
        }
    }

    // Template Method
    public abstract class ReporteTemplate
    {
        public void GenerarReporte(IEnumerable<InventarioDTO> datos, string rutaArchivo)
        {
            if (datos == null) 
            {
                return;
            }
            string contenido = FormatearDatos(datos);
            GuardarArchivo(contenido, rutaArchivo);
        }

        protected abstract string FormatearDatos(IEnumerable<InventarioDTO> datos);

        private void GuardarArchivo(string contenido, string rutaArchivo)
        {
            System.IO.File.WriteAllText(rutaArchivo, contenido, System.Text.Encoding.UTF8);
        }
    }

    public class ReporteCSV : ReporteTemplate
    {
        protected override string FormatearDatos(IEnumerable<InventarioDTO> datos)
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("ID_LOTE,NOMBRE,CATEGORIA,CANTIDAD,UNIDAD,FECHA_INGRESO,FECHA_CADUCIDAD");
            foreach (var item in datos)
            {
                sb.AppendLine($"{item.ID_LOTE},{item.NOMBRE},{item.CATEGORIA},{item.CANTIDAD},{item.UNIDAD_MEDIDA},{item.FECHA_INGRESO:yyyy-MM-dd},{item.FECHA_CADUCIDAD:yyyy-MM-dd}");
            }
            return sb.ToString();
        }
    }

    // Factory Method
    public static class ReporteFactory
    {
        public static ReporteTemplate CrearReporte(string tipo)
        {
            if (tipo.ToUpper() == "CSV")
            {
                return new ReporteCSV();
            }
            throw new ArgumentException("Tipo de reporte no soportado");
        }
    }
}